// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.0
// - protoc             v4.24.4
// source: user/v1/user.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationUserFigureEdit = "/api.user.v1.User/FigureEdit"
const OperationUserRaceRecordList = "/api.user.v1.User/RaceRecordList"

type UserHTTPServer interface {
	// FigureEdit 修改形象
	FigureEdit(context.Context, *FigureEditRequest) (*FigureEditReply, error)
	// RaceRecordList 战绩
	RaceRecordList(context.Context, *RaceRecordListRequest) (*RaceRecordListReply, error)
}

func RegisterUserHTTPServer(s *http.Server, srv UserHTTPServer) {
	r := s.Route("/")
	r.POST("/st-games/v1/user/race/record", _User_RaceRecordList0_HTTP_Handler(srv))
	r.POST("/st-games/v1/user/figure/edit", _User_FigureEdit0_HTTP_Handler(srv))
}

func _User_RaceRecordList0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RaceRecordListRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserRaceRecordList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RaceRecordList(ctx, req.(*RaceRecordListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RaceRecordListReply)
		return ctx.Result(200, reply)
	}
}

func _User_FigureEdit0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FigureEditRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserFigureEdit)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FigureEdit(ctx, req.(*FigureEditRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FigureEditReply)
		return ctx.Result(200, reply)
	}
}

type UserHTTPClient interface {
	FigureEdit(ctx context.Context, req *FigureEditRequest, opts ...http.CallOption) (rsp *FigureEditReply, err error)
	RaceRecordList(ctx context.Context, req *RaceRecordListRequest, opts ...http.CallOption) (rsp *RaceRecordListReply, err error)
}

type UserHTTPClientImpl struct {
	cc *http.Client
}

func NewUserHTTPClient(client *http.Client) UserHTTPClient {
	return &UserHTTPClientImpl{client}
}

func (c *UserHTTPClientImpl) FigureEdit(ctx context.Context, in *FigureEditRequest, opts ...http.CallOption) (*FigureEditReply, error) {
	var out FigureEditReply
	pattern := "/st-games/v1/user/figure/edit"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserFigureEdit))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserHTTPClientImpl) RaceRecordList(ctx context.Context, in *RaceRecordListRequest, opts ...http.CallOption) (*RaceRecordListReply, error) {
	var out RaceRecordListReply
	pattern := "/st-games/v1/user/race/record"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserRaceRecordList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
