// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.0
// - protoc             v4.24.4
// source: bag/v1/bag.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationBagListEmoji = "/api.bag.v1.Bag/ListEmoji"
const OperationBagListItem = "/api.bag.v1.Bag/ListItem"
const OperationBagUseEmoji = "/api.bag.v1.Bag/UseEmoji"

type BagHTTPServer interface {
	// ListEmoji 表情列表
	ListEmoji(context.Context, *ListEmojiRequest) (*ListEmojiReply, error)
	// ListItem 背包道具列表
	// 获取道具列表
	ListItem(context.Context, *ItemListRequest) (*ItemListReply, error)
	// UseEmoji 使用表情
	UseEmoji(context.Context, *UseEmojiRequest) (*UseEmojiReply, error)
}

func RegisterBagHTTPServer(s *http.Server, srv BagHTTPServer) {
	r := s.Route("/")
	r.POST("/st-games/v1/bag/item/list", _Bag_ListItem0_HTTP_Handler(srv))
	r.POST("/st-games/v1/bag/emoji/list", _Bag_ListEmoji0_HTTP_Handler(srv))
	r.POST("/st-games/v1/bag/emoji/use", _Bag_UseEmoji0_HTTP_Handler(srv))
}

func _Bag_ListItem0_HTTP_Handler(srv BagHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ItemListRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBagListItem)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListItem(ctx, req.(*ItemListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ItemListReply)
		return ctx.Result(200, reply)
	}
}

func _Bag_ListEmoji0_HTTP_Handler(srv BagHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListEmojiRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBagListEmoji)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListEmoji(ctx, req.(*ListEmojiRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListEmojiReply)
		return ctx.Result(200, reply)
	}
}

func _Bag_UseEmoji0_HTTP_Handler(srv BagHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UseEmojiRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBagUseEmoji)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UseEmoji(ctx, req.(*UseEmojiRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UseEmojiReply)
		return ctx.Result(200, reply)
	}
}

type BagHTTPClient interface {
	ListEmoji(ctx context.Context, req *ListEmojiRequest, opts ...http.CallOption) (rsp *ListEmojiReply, err error)
	ListItem(ctx context.Context, req *ItemListRequest, opts ...http.CallOption) (rsp *ItemListReply, err error)
	UseEmoji(ctx context.Context, req *UseEmojiRequest, opts ...http.CallOption) (rsp *UseEmojiReply, err error)
}

type BagHTTPClientImpl struct {
	cc *http.Client
}

func NewBagHTTPClient(client *http.Client) BagHTTPClient {
	return &BagHTTPClientImpl{client}
}

func (c *BagHTTPClientImpl) ListEmoji(ctx context.Context, in *ListEmojiRequest, opts ...http.CallOption) (*ListEmojiReply, error) {
	var out ListEmojiReply
	pattern := "/st-games/v1/bag/emoji/list"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBagListEmoji))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BagHTTPClientImpl) ListItem(ctx context.Context, in *ItemListRequest, opts ...http.CallOption) (*ItemListReply, error) {
	var out ItemListReply
	pattern := "/st-games/v1/bag/item/list"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBagListItem))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BagHTTPClientImpl) UseEmoji(ctx context.Context, in *UseEmojiRequest, opts ...http.CallOption) (*UseEmojiReply, error) {
	var out UseEmojiReply
	pattern := "/st-games/v1/bag/emoji/use"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBagUseEmoji))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
