// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: game/v1/game.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	v1 "github.com/lulu-ls/st-api/api/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 公告类别
type AnnouncementType int32

const (
	AnnouncementType__1    AnnouncementType = 0 // 未知
	AnnouncementType_Text  AnnouncementType = 1 // 文本
	AnnouncementType_Image AnnouncementType = 2 // 图片
)

// Enum value maps for AnnouncementType.
var (
	AnnouncementType_name = map[int32]string{
		0: "_1",
		1: "Text",
		2: "Image",
	}
	AnnouncementType_value = map[string]int32{
		"_1":    0,
		"Text":  1,
		"Image": 2,
	}
)

func (x AnnouncementType) Enum() *AnnouncementType {
	p := new(AnnouncementType)
	*p = x
	return p
}

func (x AnnouncementType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnnouncementType) Descriptor() protoreflect.EnumDescriptor {
	return file_game_v1_game_proto_enumTypes[0].Descriptor()
}

func (AnnouncementType) Type() protoreflect.EnumType {
	return &file_game_v1_game_proto_enumTypes[0]
}

func (x AnnouncementType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnnouncementType.Descriptor instead.
func (AnnouncementType) EnumDescriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{0}
}

// 任务进度状态
type TaskStatus int32

const (
	TaskStatus_undone   TaskStatus = 0 // 未完成
	TaskStatus_done     TaskStatus = 1 // 已完成
	TaskStatus_received TaskStatus = 2 // 已发放奖励
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "undone",
		1: "done",
		2: "received",
	}
	TaskStatus_value = map[string]int32{
		"undone":   0,
		"done":     1,
		"received": 2,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_game_v1_game_proto_enumTypes[1].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_game_v1_game_proto_enumTypes[1]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{1}
}

// 任务刷新周期 0无 1 天 2周 3 月
type RefreshCycle int32

const (
	RefreshCycle_none  RefreshCycle = 0
	RefreshCycle_day   RefreshCycle = 1
	RefreshCycle_week  RefreshCycle = 2
	RefreshCycle_month RefreshCycle = 3
)

// Enum value maps for RefreshCycle.
var (
	RefreshCycle_name = map[int32]string{
		0: "none",
		1: "day",
		2: "week",
		3: "month",
	}
	RefreshCycle_value = map[string]int32{
		"none":  0,
		"day":   1,
		"week":  2,
		"month": 3,
	}
)

func (x RefreshCycle) Enum() *RefreshCycle {
	p := new(RefreshCycle)
	*p = x
	return p
}

func (x RefreshCycle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RefreshCycle) Descriptor() protoreflect.EnumDescriptor {
	return file_game_v1_game_proto_enumTypes[2].Descriptor()
}

func (RefreshCycle) Type() protoreflect.EnumType {
	return &file_game_v1_game_proto_enumTypes[2]
}

func (x RefreshCycle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RefreshCycle.Descriptor instead.
func (RefreshCycle) EnumDescriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{2}
}

// 游戏类型
type GameType int32

const (
	GameType_GameTypeUnspecified GameType = 0
	GameType_GameTypeDigHole     GameType = 1 //挖坑
	GameType_GameTypeLandlord    GameType = 2 //斗地主
	GameType_GameTypeMahjong     GameType = 3 //麻将
)

// Enum value maps for GameType.
var (
	GameType_name = map[int32]string{
		0: "GameTypeUnspecified",
		1: "GameTypeDigHole",
		2: "GameTypeLandlord",
		3: "GameTypeMahjong",
	}
	GameType_value = map[string]int32{
		"GameTypeUnspecified": 0,
		"GameTypeDigHole":     1,
		"GameTypeLandlord":    2,
		"GameTypeMahjong":     3,
	}
)

func (x GameType) Enum() *GameType {
	p := new(GameType)
	*p = x
	return p
}

func (x GameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameType) Descriptor() protoreflect.EnumDescriptor {
	return file_game_v1_game_proto_enumTypes[3].Descriptor()
}

func (GameType) Type() protoreflect.EnumType {
	return &file_game_v1_game_proto_enumTypes[3]
}

func (x GameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameType.Descriptor instead.
func (GameType) EnumDescriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{3}
}

// 游戏类别
type GameCategory int32

const (
	GameCategory_GameCategoryUnspecified GameCategory = 0
	GameCategory_GameCategoryGold        GameCategory = 1 //金币场（自由场）
	GameCategory_GameCategoryCompetition GameCategory = 2 //竞技场
	GameCategory_GameCategoryPrivate     GameCategory = 3 //好友房
)

// Enum value maps for GameCategory.
var (
	GameCategory_name = map[int32]string{
		0: "GameCategoryUnspecified",
		1: "GameCategoryGold",
		2: "GameCategoryCompetition",
		3: "GameCategoryPrivate",
	}
	GameCategory_value = map[string]int32{
		"GameCategoryUnspecified": 0,
		"GameCategoryGold":        1,
		"GameCategoryCompetition": 2,
		"GameCategoryPrivate":     3,
	}
)

func (x GameCategory) Enum() *GameCategory {
	p := new(GameCategory)
	*p = x
	return p
}

func (x GameCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_game_v1_game_proto_enumTypes[4].Descriptor()
}

func (GameCategory) Type() protoreflect.EnumType {
	return &file_game_v1_game_proto_enumTypes[4]
}

func (x GameCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameCategory.Descriptor instead.
func (GameCategory) EnumDescriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{4}
}

// 游戏通知
type GameNotifyType int32

const (
	GameNotifyType__2            GameNotifyType = 0
	GameNotifyType_RegisterAward GameNotifyType = 1 // 注册奖励
)

// Enum value maps for GameNotifyType.
var (
	GameNotifyType_name = map[int32]string{
		0: "_2",
		1: "RegisterAward",
	}
	GameNotifyType_value = map[string]int32{
		"_2":            0,
		"RegisterAward": 1,
	}
)

func (x GameNotifyType) Enum() *GameNotifyType {
	p := new(GameNotifyType)
	*p = x
	return p
}

func (x GameNotifyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameNotifyType) Descriptor() protoreflect.EnumDescriptor {
	return file_game_v1_game_proto_enumTypes[5].Descriptor()
}

func (GameNotifyType) Type() protoreflect.EnumType {
	return &file_game_v1_game_proto_enumTypes[5]
}

func (x GameNotifyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameNotifyType.Descriptor instead.
func (GameNotifyType) EnumDescriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{5}
}

// 设备类型
type DeviceType int32

const (
	DeviceType__4      DeviceType = 0 // 忽略
	DeviceType_Android DeviceType = 1 // 安卓
	DeviceType_iOS     DeviceType = 2 // ios
	DeviceType_Windows DeviceType = 3 // Windows
)

// Enum value maps for DeviceType.
var (
	DeviceType_name = map[int32]string{
		0: "_4",
		1: "Android",
		2: "iOS",
		3: "Windows",
	}
	DeviceType_value = map[string]int32{
		"_4":      0,
		"Android": 1,
		"iOS":     2,
		"Windows": 3,
	}
)

func (x DeviceType) Enum() *DeviceType {
	p := new(DeviceType)
	*p = x
	return p
}

func (x DeviceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceType) Descriptor() protoreflect.EnumDescriptor {
	return file_game_v1_game_proto_enumTypes[6].Descriptor()
}

func (DeviceType) Type() protoreflect.EnumType {
	return &file_game_v1_game_proto_enumTypes[6]
}

func (x DeviceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceType.Descriptor instead.
func (DeviceType) EnumDescriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{6}
}

// 版本类型
type VersionType int32

const (
	VersionType__3      VersionType = 0
	VersionType_audit   VersionType = 1 // 审核版本
	VersionType_develop VersionType = 2 // 开发版
	VersionType_trial   VersionType = 3 // 体验版本
	VersionType_release VersionType = 4 // 正式版
)

// Enum value maps for VersionType.
var (
	VersionType_name = map[int32]string{
		0: "_3",
		1: "audit",
		2: "develop",
		3: "trial",
		4: "release",
	}
	VersionType_value = map[string]int32{
		"_3":      0,
		"audit":   1,
		"develop": 2,
		"trial":   3,
		"release": 4,
	}
)

func (x VersionType) Enum() *VersionType {
	p := new(VersionType)
	*p = x
	return p
}

func (x VersionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VersionType) Descriptor() protoreflect.EnumDescriptor {
	return file_game_v1_game_proto_enumTypes[7].Descriptor()
}

func (VersionType) Type() protoreflect.EnumType {
	return &file_game_v1_game_proto_enumTypes[7]
}

func (x VersionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VersionType.Descriptor instead.
func (VersionType) EnumDescriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{7}
}

// 活动类型 跳转类型：1:url 2:game_category_id 3:game_config_id 4:game_free_config_id  5:recharge 6:share 7：task
type TaskAction int32

const (
	TaskAction__                TaskAction = 0
	TaskAction_URL              TaskAction = 1
	TaskAction_GAME_CATEGORY    TaskAction = 2
	TaskAction_GAME_CONFIG      TaskAction = 3
	TaskAction_GAME_FREE_CONFIG TaskAction = 4
	TaskAction_RECHARGE         TaskAction = 5
	TaskAction_SHARE            TaskAction = 6
	TaskAction_TASK             TaskAction = 7
)

// Enum value maps for TaskAction.
var (
	TaskAction_name = map[int32]string{
		0: "_",
		1: "URL",
		2: "GAME_CATEGORY",
		3: "GAME_CONFIG",
		4: "GAME_FREE_CONFIG",
		5: "RECHARGE",
		6: "SHARE",
		7: "TASK",
	}
	TaskAction_value = map[string]int32{
		"_":                0,
		"URL":              1,
		"GAME_CATEGORY":    2,
		"GAME_CONFIG":      3,
		"GAME_FREE_CONFIG": 4,
		"RECHARGE":         5,
		"SHARE":            6,
		"TASK":             7,
	}
)

func (x TaskAction) Enum() *TaskAction {
	p := new(TaskAction)
	*p = x
	return p
}

func (x TaskAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskAction) Descriptor() protoreflect.EnumDescriptor {
	return file_game_v1_game_proto_enumTypes[8].Descriptor()
}

func (TaskAction) Type() protoreflect.EnumType {
	return &file_game_v1_game_proto_enumTypes[8]
}

func (x TaskAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskAction.Descriptor instead.
func (TaskAction) EnumDescriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{8}
}

// 任务配置类型 1game 2recharge
type TaskType int32

const (
	TaskType__5         TaskType = 0
	TaskType_GAME       TaskType = 1
	TaskType_T_RECHARGE TaskType = 2
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "_5",
		1: "GAME",
		2: "T_RECHARGE",
	}
	TaskType_value = map[string]int32{
		"_5":         0,
		"GAME":       1,
		"T_RECHARGE": 2,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_game_v1_game_proto_enumTypes[9].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_game_v1_game_proto_enumTypes[9]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{9}
}

// 充值类型 1指定金额次数 2累计金额
type TaskRechargeType int32

const (
	TaskRechargeType__6    TaskRechargeType = 0
	TaskRechargeType_FIX   TaskRechargeType = 1
	TaskRechargeType_TOTAL TaskRechargeType = 2
)

// Enum value maps for TaskRechargeType.
var (
	TaskRechargeType_name = map[int32]string{
		0: "_6",
		1: "FIX",
		2: "TOTAL",
	}
	TaskRechargeType_value = map[string]int32{
		"_6":    0,
		"FIX":   1,
		"TOTAL": 2,
	}
)

func (x TaskRechargeType) Enum() *TaskRechargeType {
	p := new(TaskRechargeType)
	*p = x
	return p
}

func (x TaskRechargeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskRechargeType) Descriptor() protoreflect.EnumDescriptor {
	return file_game_v1_game_proto_enumTypes[10].Descriptor()
}

func (TaskRechargeType) Type() protoreflect.EnumType {
	return &file_game_v1_game_proto_enumTypes[10]
}

func (x TaskRechargeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskRechargeType.Descriptor instead.
func (TaskRechargeType) EnumDescriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{10}
}

// 游戏奖励类型 1:对局2：胜场3：排名
type TaskGameType int32

const (
	TaskGameType__7   TaskGameType = 0
	TaskGameType_PLAY TaskGameType = 1
	TaskGameType_WIN  TaskGameType = 2
	TaskGameType_RANK TaskGameType = 3
)

// Enum value maps for TaskGameType.
var (
	TaskGameType_name = map[int32]string{
		0: "_7",
		1: "PLAY",
		2: "WIN",
		3: "RANK",
	}
	TaskGameType_value = map[string]int32{
		"_7":   0,
		"PLAY": 1,
		"WIN":  2,
		"RANK": 3,
	}
)

func (x TaskGameType) Enum() *TaskGameType {
	p := new(TaskGameType)
	*p = x
	return p
}

func (x TaskGameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskGameType) Descriptor() protoreflect.EnumDescriptor {
	return file_game_v1_game_proto_enumTypes[11].Descriptor()
}

func (TaskGameType) Type() protoreflect.EnumType {
	return &file_game_v1_game_proto_enumTypes[11]
}

func (x TaskGameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskGameType.Descriptor instead.
func (TaskGameType) EnumDescriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{11}
}

type AnnouncementListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page      *v1.Paginate `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	AppId     int32        `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`             // app id
	ChannelId int32        `protobuf:"varint,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"` // channel id
}

func (x *AnnouncementListRequest) Reset() {
	*x = AnnouncementListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_v1_game_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnnouncementListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnouncementListRequest) ProtoMessage() {}

func (x *AnnouncementListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnouncementListRequest.ProtoReflect.Descriptor instead.
func (*AnnouncementListRequest) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{0}
}

func (x *AnnouncementListRequest) GetPage() *v1.Paginate {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *AnnouncementListRequest) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *AnnouncementListRequest) GetChannelId() int32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

type AnnouncementListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*AnnouncementListItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`    // 列表
	Total int32                   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 合计
}

func (x *AnnouncementListReply) Reset() {
	*x = AnnouncementListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_v1_game_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnnouncementListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnouncementListReply) ProtoMessage() {}

func (x *AnnouncementListReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnouncementListReply.ProtoReflect.Descriptor instead.
func (*AnnouncementListReply) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{1}
}

func (x *AnnouncementListReply) GetList() []*AnnouncementListItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *AnnouncementListReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type AnnouncementListItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                       // 通知 id
	Title       string           `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                                  // 标题
	Information string           `protobuf:"bytes,3,opt,name=information,proto3" json:"information,omitempty"`                      // 内容
	Image       string           `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`                                  // 图片
	Type        AnnouncementType `protobuf:"varint,5,opt,name=type,proto3,enum=api.game.v1.AnnouncementType" json:"type,omitempty"` // 类型
	Subtitle    string           `protobuf:"bytes,6,opt,name=subtitle,proto3" json:"subtitle,omitempty"`                            // 副标题
}

func (x *AnnouncementListItem) Reset() {
	*x = AnnouncementListItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_v1_game_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnnouncementListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnouncementListItem) ProtoMessage() {}

func (x *AnnouncementListItem) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnouncementListItem.ProtoReflect.Descriptor instead.
func (*AnnouncementListItem) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{2}
}

func (x *AnnouncementListItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AnnouncementListItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AnnouncementListItem) GetInformation() string {
	if x != nil {
		return x.Information
	}
	return ""
}

func (x *AnnouncementListItem) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *AnnouncementListItem) GetType() AnnouncementType {
	if x != nil {
		return x.Type
	}
	return AnnouncementType__1
}

func (x *AnnouncementListItem) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

type ActivityListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page      *v1.Paginate `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	AppId     int32        `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`             // app id
	ChannelId int32        `protobuf:"varint,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"` // channel id
	UserId    int64        `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // 用户 id
}

func (x *ActivityListRequest) Reset() {
	*x = ActivityListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_v1_game_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivityListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityListRequest) ProtoMessage() {}

func (x *ActivityListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityListRequest.ProtoReflect.Descriptor instead.
func (*ActivityListRequest) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{3}
}

func (x *ActivityListRequest) GetPage() *v1.Paginate {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ActivityListRequest) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *ActivityListRequest) GetChannelId() int32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *ActivityListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ActivityListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*ActivityListItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`    // 列表
	Total int32               `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 数量
}

func (x *ActivityListReply) Reset() {
	*x = ActivityListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_v1_game_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivityListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityListReply) ProtoMessage() {}

func (x *ActivityListReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityListReply.ProtoReflect.Descriptor instead.
func (*ActivityListReply) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{4}
}

func (x *ActivityListReply) GetList() []*ActivityListItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ActivityListReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ActivityListItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId  int32  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"` // 配置 id
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                              // 标题
	Subtitle    string `protobuf:"bytes,3,opt,name=subtitle,proto3" json:"subtitle,omitempty"`                        // 子标题
	Information string `protobuf:"bytes,4,opt,name=information,proto3" json:"information,omitempty"`                  // 描述
	Image       string `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`                              // 图片
}

func (x *ActivityListItem) Reset() {
	*x = ActivityListItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_v1_game_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivityListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityListItem) ProtoMessage() {}

func (x *ActivityListItem) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityListItem.ProtoReflect.Descriptor instead.
func (*ActivityListItem) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{5}
}

func (x *ActivityListItem) GetActivityId() int32 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *ActivityListItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ActivityListItem) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

func (x *ActivityListItem) GetInformation() string {
	if x != nil {
		return x.Information
	}
	return ""
}

func (x *ActivityListItem) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type TaskDetailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId      int32 `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`                // app id
	ChannelId  int32 `protobuf:"varint,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`    // channel id
	UserId     int64 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // 用户 id  [(validate.rules).int64.gt =  0]
	ActivityId int32 `protobuf:"varint,5,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"` // 配置 id
}

func (x *TaskDetailRequest) Reset() {
	*x = TaskDetailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_v1_game_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDetailRequest) ProtoMessage() {}

func (x *TaskDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDetailRequest.ProtoReflect.Descriptor instead.
func (*TaskDetailRequest) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{6}
}

func (x *TaskDetailRequest) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *TaskDetailRequest) GetChannelId() int32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *TaskDetailRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TaskDetailRequest) GetActivityId() int32 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

type TaskDetailReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*TaskListItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"` // 活动任务列表
}

func (x *TaskDetailReply) Reset() {
	*x = TaskDetailReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_v1_game_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskDetailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDetailReply) ProtoMessage() {}

func (x *TaskDetailReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDetailReply.ProtoReflect.Descriptor instead.
func (*TaskDetailReply) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{7}
}

func (x *TaskDetailReply) GetList() []*TaskListItem {
	if x != nil {
		return x.List
	}
	return nil
}

type TaskListItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId  int32      `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`               // 配置 id
	Title   string     `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                                // 标题
	Action  int32      `protobuf:"varint,3,opt,name=action,proto3" json:"action,omitempty"`                             // 跳转方式 // 跳转类型：1:url 2:game_category_id 3:game_config_id 4:game_free_config_id  5:recharge 6:share 7：task
	Url     string     `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`                                    // 跳转地址 action = 1
	Number  int32      `protobuf:"varint,5,opt,name=number,proto3" json:"number,omitempty"`                             // 任务需要完成数量
	Process int32      `protobuf:"varint,6,opt,name=process,proto3" json:"process,omitempty"`                           // 当前完成进度
	Status  TaskStatus `protobuf:"varint,7,opt,name=status,proto3,enum=api.game.v1.TaskStatus" json:"status,omitempty"` // 状态
	//	 double amount = 7; // 需要充值金额 action = 5
	//		double process_amount = 8; // 已充值金额
	Award []*TaskListAwardItem `protobuf:"bytes,8,rep,name=award,proto3" json:"award,omitempty"` // 奖励
}

func (x *TaskListItem) Reset() {
	*x = TaskListItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_v1_game_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskListItem) ProtoMessage() {}

func (x *TaskListItem) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskListItem.ProtoReflect.Descriptor instead.
func (*TaskListItem) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{8}
}

func (x *TaskListItem) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskListItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TaskListItem) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *TaskListItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *TaskListItem) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *TaskListItem) GetProcess() int32 {
	if x != nil {
		return x.Process
	}
	return 0
}

func (x *TaskListItem) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_undone
}

func (x *TaskListItem) GetAward() []*TaskListAwardItem {
	if x != nil {
		return x.Award
	}
	return nil
}

type TaskListAwardItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId   int32  `protobuf:"varint,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"` // 道具 id
	Name     string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                    // 奖励道具名称
	Image    string `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`                  // 奖励道具图片
	Quantity int32  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`           // 奖励道具数量
}

func (x *TaskListAwardItem) Reset() {
	*x = TaskListAwardItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_v1_game_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskListAwardItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskListAwardItem) ProtoMessage() {}

func (x *TaskListAwardItem) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskListAwardItem.ProtoReflect.Descriptor instead.
func (*TaskListAwardItem) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{9}
}

func (x *TaskListAwardItem) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *TaskListAwardItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskListAwardItem) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *TaskListAwardItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type TaskRewardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int64   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`           // 用户 id
	TaskIds []int32 `protobuf:"varint,2,rep,packed,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"` // 任务 id
}

func (x *TaskRewardRequest) Reset() {
	*x = TaskRewardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_v1_game_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskRewardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRewardRequest) ProtoMessage() {}

func (x *TaskRewardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRewardRequest.ProtoReflect.Descriptor instead.
func (*TaskRewardRequest) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{10}
}

func (x *TaskRewardRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TaskRewardRequest) GetTaskIds() []int32 {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

type TaskRewardReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TaskRewardReply) Reset() {
	*x = TaskRewardReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_v1_game_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskRewardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRewardReply) ProtoMessage() {}

func (x *TaskRewardReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRewardReply.ProtoReflect.Descriptor instead.
func (*TaskRewardReply) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{11}
}

type GameInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId     int32 `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`             // app id
	ChannelId int32 `protobuf:"varint,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"` // channel id
	UserId    int64 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // 用户 id
}

func (x *GameInfoRequest) Reset() {
	*x = GameInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_v1_game_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInfoRequest) ProtoMessage() {}

func (x *GameInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInfoRequest.ProtoReflect.Descriptor instead.
func (*GameInfoRequest) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{12}
}

func (x *GameInfoRequest) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *GameInfoRequest) GetChannelId() int32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *GameInfoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GameInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InGame       bool         `protobuf:"varint,1,opt,name=in_game,json=inGame,proto3" json:"in_game,omitempty"`                                                 // 是否在游戏中
	GameId       string       `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`                                                  // 游戏 id
	GameType     GameType     `protobuf:"varint,3,opt,name=game_type,json=gameType,proto3,enum=api.game.v1.GameType" json:"game_type,omitempty"`                 // 游戏类型
	GameCategory GameCategory `protobuf:"varint,4,opt,name=game_category,json=gameCategory,proto3,enum=api.game.v1.GameCategory" json:"game_category,omitempty"` // 游戏类别
	TableId      string       `protobuf:"bytes,5,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`                                               // 桌号
}

func (x *GameInfoReply) Reset() {
	*x = GameInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_v1_game_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInfoReply) ProtoMessage() {}

func (x *GameInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInfoReply.ProtoReflect.Descriptor instead.
func (*GameInfoReply) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{13}
}

func (x *GameInfoReply) GetInGame() bool {
	if x != nil {
		return x.InGame
	}
	return false
}

func (x *GameInfoReply) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameInfoReply) GetGameType() GameType {
	if x != nil {
		return x.GameType
	}
	return GameType_GameTypeUnspecified
}

func (x *GameInfoReply) GetGameCategory() GameCategory {
	if x != nil {
		return x.GameCategory
	}
	return GameCategory_GameCategoryUnspecified
}

func (x *GameInfoReply) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

type GetGameNotifyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId      int32          `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`                                                // app id
	ChannelId  int32          `protobuf:"varint,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`                                    // channel id
	UserId     int64          `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                             // 用户 id
	NotifyType GameNotifyType `protobuf:"varint,5,opt,name=notify_type,json=notifyType,proto3,enum=api.game.v1.GameNotifyType" json:"notify_type,omitempty"` // 通知类型
}

func (x *GetGameNotifyRequest) Reset() {
	*x = GetGameNotifyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_v1_game_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameNotifyRequest) ProtoMessage() {}

func (x *GetGameNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameNotifyRequest.ProtoReflect.Descriptor instead.
func (*GetGameNotifyRequest) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{14}
}

func (x *GetGameNotifyRequest) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *GetGameNotifyRequest) GetChannelId() int32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *GetGameNotifyRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetGameNotifyRequest) GetNotifyType() GameNotifyType {
	if x != nil {
		return x.NotifyType
	}
	return GameNotifyType__2
}

type GetGameNotifyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsShow bool `protobuf:"varint,1,opt,name=is_show,json=isShow,proto3" json:"is_show,omitempty"` // 是否展示
}

func (x *GetGameNotifyReply) Reset() {
	*x = GetGameNotifyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_v1_game_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameNotifyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameNotifyReply) ProtoMessage() {}

func (x *GetGameNotifyReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameNotifyReply.ProtoReflect.Descriptor instead.
func (*GetGameNotifyReply) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{15}
}

func (x *GetGameNotifyReply) GetIsShow() bool {
	if x != nil {
		return x.IsShow
	}
	return false
}

type ReadGameNotifyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId      int32          `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`                                                // app id
	ChannelId  int32          `protobuf:"varint,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`                                    // channel id
	UserId     int64          `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                             // 用户 id
	NotifyType GameNotifyType `protobuf:"varint,5,opt,name=notify_type,json=notifyType,proto3,enum=api.game.v1.GameNotifyType" json:"notify_type,omitempty"` // 通知类型
}

func (x *ReadGameNotifyRequest) Reset() {
	*x = ReadGameNotifyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_v1_game_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadGameNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadGameNotifyRequest) ProtoMessage() {}

func (x *ReadGameNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadGameNotifyRequest.ProtoReflect.Descriptor instead.
func (*ReadGameNotifyRequest) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{16}
}

func (x *ReadGameNotifyRequest) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *ReadGameNotifyRequest) GetChannelId() int32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *ReadGameNotifyRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReadGameNotifyRequest) GetNotifyType() GameNotifyType {
	if x != nil {
		return x.NotifyType
	}
	return GameNotifyType__2
}

type ReadGameNotifyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadGameNotifyReply) Reset() {
	*x = ReadGameNotifyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_v1_game_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadGameNotifyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadGameNotifyReply) ProtoMessage() {}

func (x *ReadGameNotifyReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadGameNotifyReply.ProtoReflect.Descriptor instead.
func (*ReadGameNotifyReply) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{17}
}

type GetAppConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId       int32       `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`                                                // app id
	ChannelId   int32       `protobuf:"varint,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`                                    // channel id
	Version     string      `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`                                                          // 版本 id
	Device      DeviceType  `protobuf:"varint,5,opt,name=device,proto3,enum=api.game.v1.DeviceType" json:"device,omitempty"`                               // 1 android 2 ios
	VersionType VersionType `protobuf:"varint,6,opt,name=version_type,json=versionType,proto3,enum=api.game.v1.VersionType" json:"version_type,omitempty"` // 配置类型
}

func (x *GetAppConfigRequest) Reset() {
	*x = GetAppConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_v1_game_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAppConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppConfigRequest) ProtoMessage() {}

func (x *GetAppConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppConfigRequest.ProtoReflect.Descriptor instead.
func (*GetAppConfigRequest) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{18}
}

func (x *GetAppConfigRequest) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *GetAppConfigRequest) GetChannelId() int32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *GetAppConfigRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetAppConfigRequest) GetDevice() DeviceType {
	if x != nil {
		return x.Device
	}
	return DeviceType__4
}

func (x *GetAppConfigRequest) GetVersionType() VersionType {
	if x != nil {
		return x.VersionType
	}
	return VersionType__3
}

type GetAppConfigReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*GetAppConfigItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"` // 列表
}

func (x *GetAppConfigReply) Reset() {
	*x = GetAppConfigReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_v1_game_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAppConfigReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppConfigReply) ProtoMessage() {}

func (x *GetAppConfigReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppConfigReply.ProtoReflect.Descriptor instead.
func (*GetAppConfigReply) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{19}
}

func (x *GetAppConfigReply) GetList() []*GetAppConfigItem {
	if x != nil {
		return x.List
	}
	return nil
}

type GetAppConfigItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppConfigId int32  `protobuf:"varint,1,opt,name=app_config_id,json=appConfigId,proto3" json:"app_config_id,omitempty"` // 字典 id
	Key         string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`                                       // 键
	Value       string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`                                   // 值
}

func (x *GetAppConfigItem) Reset() {
	*x = GetAppConfigItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_v1_game_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAppConfigItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppConfigItem) ProtoMessage() {}

func (x *GetAppConfigItem) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppConfigItem.ProtoReflect.Descriptor instead.
func (*GetAppConfigItem) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{20}
}

func (x *GetAppConfigItem) GetAppConfigId() int32 {
	if x != nil {
		return x.AppConfigId
	}
	return 0
}

func (x *GetAppConfigItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetAppConfigItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CheckSignupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       int64 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                     // 用户 id
	GameConfigId int32 `protobuf:"varint,4,opt,name=game_config_id,json=gameConfigId,proto3" json:"game_config_id,omitempty"` // 游戏配置 id
}

func (x *CheckSignupRequest) Reset() {
	*x = CheckSignupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_v1_game_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckSignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSignupRequest) ProtoMessage() {}

func (x *CheckSignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSignupRequest.ProtoReflect.Descriptor instead.
func (*CheckSignupRequest) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{21}
}

func (x *CheckSignupRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckSignupRequest) GetGameConfigId() int32 {
	if x != nil {
		return x.GameConfigId
	}
	return 0
}

type CheckSignupReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CheckSignupReply) Reset() {
	*x = CheckSignupReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_v1_game_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckSignupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSignupReply) ProtoMessage() {}

func (x *CheckSignupReply) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSignupReply.ProtoReflect.Descriptor instead.
func (*CheckSignupReply) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{22}
}

var File_game_v1_game_proto protoreflect.FileDescriptor

var file_game_v1_game_proto_rawDesc = []byte{
	0x0a, 0x12, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76,
	0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e,
	0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x16, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x7c, 0x0a, 0x17, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61,
	0x74, 0x65, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x22, 0x64,
	0x0a, 0x15, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x35, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x6d, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x22, 0xc3, 0x01, 0x0a, 0x14, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x31, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x73, 0x75, 0x62, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x73, 0x75, 0x62, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x91, 0x01, 0x0a, 0x13, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2b, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12,
	0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x5c,
	0x0a, 0x11, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x31, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x9d, 0x01, 0x0a,
	0x10, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x75, 0x62, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x75, 0x62, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x8c, 0x01, 0x0a,
	0x11, 0x54, 0x61, 0x73, 0x6b, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x28, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x1a, 0x02, 0x20, 0x00, 0x52,
	0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x22, 0x40, 0x0a, 0x0f, 0x54,
	0x61, 0x73, 0x6b, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2d,
	0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x4c,
	0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x80, 0x02,
	0x0a, 0x0c, 0x54, 0x61, 0x73, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x17,
	0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x2f, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x34, 0x0a, 0x05, 0x61, 0x77,
	0x61, 0x72, 0x64, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x4c, 0x69, 0x73, 0x74,
	0x41, 0x77, 0x61, 0x72, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x61, 0x77, 0x61, 0x72, 0x64,
	0x22, 0x72, 0x0a, 0x11, 0x54, 0x61, 0x73, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x77, 0x61, 0x72,
	0x64, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x22, 0x57, 0x0a, 0x11, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x29, 0x0a, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x05, 0x42, 0x0e, 0xfa, 0x42, 0x0b, 0x92, 0x01, 0x08, 0x08, 0x01, 0x22, 0x04,
	0x1a, 0x02, 0x20, 0x00, 0x52, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x73, 0x22, 0x11, 0x0a,
	0x0f, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x60, 0x0a, 0x0f, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x22, 0xd0, 0x01, 0x0a, 0x0d, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x6e, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3e, 0x0a, 0x0d, 0x67, 0x61,
	0x6d, 0x65, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x61, 0x6d, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x0c, 0x67, 0x61,
	0x6d, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x49, 0x64, 0x22, 0xa3, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d,
	0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15,
	0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x3c, 0x0a,
	0x0b, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x0a, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x54, 0x79, 0x70, 0x65, 0x22, 0x2d, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x73, 0x68, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x53, 0x68, 0x6f, 0x77, 0x22, 0xa4, 0x01, 0x0a, 0x15, 0x52,
	0x65, 0x61, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x3c, 0x0a, 0x0b, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67,
	0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x54, 0x79, 0x70,
	0x65, 0x22, 0x15, 0x0a, 0x13, 0x52, 0x65, 0x61, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0xd3, 0x01, 0x0a, 0x13, 0x47, 0x65, 0x74,
	0x41, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x2f, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x0b, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0x46,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x31, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x5e, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x22, 0x0a, 0x0d, 0x61, 0x70,
	0x70, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x61, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x53, 0x0a, 0x12, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53,
	0x69, 0x67, 0x6e, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x67,
	0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2a,
	0x2f, 0x0a, 0x10, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x5f, 0x31, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x54,
	0x65, 0x78, 0x74, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x10, 0x02,
	0x2a, 0x30, 0x0a, 0x0a, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0a,
	0x0a, 0x06, 0x75, 0x6e, 0x64, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x64, 0x6f,
	0x6e, 0x65, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64,
	0x10, 0x02, 0x2a, 0x36, 0x0a, 0x0c, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x43, 0x79, 0x63,
	0x6c, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x6e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03,
	0x64, 0x61, 0x79, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x77, 0x65, 0x65, 0x6b, 0x10, 0x02, 0x12,
	0x09, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x10, 0x03, 0x2a, 0x63, 0x0a, 0x08, 0x47, 0x61,
	0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x13, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x55, 0x6e, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x64, 0x10, 0x00, 0x12,
	0x13, 0x0a, 0x0f, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x44, 0x69, 0x67, 0x48, 0x6f,
	0x6c, 0x65, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x4c, 0x61, 0x6e, 0x64, 0x6c, 0x6f, 0x72, 0x64, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x47, 0x61,
	0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x4d, 0x61, 0x68, 0x6a, 0x6f, 0x6e, 0x67, 0x10, 0x03, 0x2a,
	0x77, 0x0a, 0x0c, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12,
	0x1b, 0x0a, 0x17, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x55,
	0x6e, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x64, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10,
	0x47, 0x61, 0x6d, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x47, 0x6f, 0x6c, 0x64,
	0x10, 0x01, 0x12, 0x1b, 0x0a, 0x17, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x43, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x02, 0x12,
	0x17, 0x0a, 0x13, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x50,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x10, 0x03, 0x2a, 0x2b, 0x0a, 0x0e, 0x47, 0x61, 0x6d, 0x65,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x5f, 0x32,
	0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x41, 0x77,
	0x61, 0x72, 0x64, 0x10, 0x01, 0x2a, 0x37, 0x0a, 0x0a, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x5f, 0x34, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x41,
	0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x69, 0x4f, 0x53, 0x10,
	0x02, 0x12, 0x0b, 0x0a, 0x07, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x73, 0x10, 0x03, 0x2a, 0x45,
	0x0a, 0x0b, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x06, 0x0a,
	0x02, 0x5f, 0x33, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x61, 0x75, 0x64, 0x69, 0x74, 0x10, 0x01,
	0x12, 0x0b, 0x0a, 0x07, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x10, 0x02, 0x12, 0x09, 0x0a,
	0x05, 0x74, 0x72, 0x69, 0x61, 0x6c, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x72, 0x65, 0x6c, 0x65,
	0x61, 0x73, 0x65, 0x10, 0x04, 0x2a, 0x79, 0x0a, 0x0a, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x05, 0x0a, 0x01, 0x5f, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x55, 0x52,
	0x4c, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x43, 0x41, 0x54, 0x45,
	0x47, 0x4f, 0x52, 0x59, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x43,
	0x4f, 0x4e, 0x46, 0x49, 0x47, 0x10, 0x03, 0x12, 0x14, 0x0a, 0x10, 0x47, 0x41, 0x4d, 0x45, 0x5f,
	0x46, 0x52, 0x45, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x47, 0x10, 0x04, 0x12, 0x0c, 0x0a,
	0x08, 0x52, 0x45, 0x43, 0x48, 0x41, 0x52, 0x47, 0x45, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05, 0x53,
	0x48, 0x41, 0x52, 0x45, 0x10, 0x06, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x41, 0x53, 0x4b, 0x10, 0x07,
	0x2a, 0x2c, 0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x06, 0x0a, 0x02,
	0x5f, 0x35, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x47, 0x41, 0x4d, 0x45, 0x10, 0x01, 0x12, 0x0e,
	0x0a, 0x0a, 0x54, 0x5f, 0x52, 0x45, 0x43, 0x48, 0x41, 0x52, 0x47, 0x45, 0x10, 0x02, 0x2a, 0x2e,
	0x0a, 0x10, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x5f, 0x36, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x46, 0x49,
	0x58, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x54, 0x4f, 0x54, 0x41, 0x4c, 0x10, 0x02, 0x2a, 0x33,
	0x0a, 0x0c, 0x54, 0x61, 0x73, 0x6b, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x06,
	0x0a, 0x02, 0x5f, 0x37, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x4c, 0x41, 0x59, 0x10, 0x01,
	0x12, 0x07, 0x0a, 0x03, 0x57, 0x49, 0x4e, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x41, 0x4e,
	0x4b, 0x10, 0x03, 0x32, 0xe1, 0x08, 0x0a, 0x04, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x8c, 0x01, 0x0a,
	0x10, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2e, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x28, 0x3a, 0x01, 0x2a, 0x22, 0x23, 0x2f, 0x73, 0x74, 0x2d, 0x67, 0x61, 0x6d, 0x65,
	0x73, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e,
	0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x7c, 0x0a, 0x0c, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x20, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2a, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x24, 0x3a, 0x01, 0x2a, 0x22, 0x1f, 0x2f, 0x73, 0x74, 0x2d, 0x67, 0x61,
	0x6d, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x78, 0x0a, 0x0a, 0x54, 0x61, 0x73,
	0x6b, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x26, 0x3a, 0x01, 0x2a,
	0x22, 0x21, 0x2f, 0x73, 0x74, 0x2d, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x67,
	0x61, 0x6d, 0x65, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x2f, 0x64, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x12, 0x74, 0x0a, 0x0a, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x28, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x22, 0x3a, 0x01, 0x2a, 0x22, 0x1d, 0x2f, 0x73, 0x74, 0x2d,
	0x67, 0x61, 0x6d, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x74, 0x61,
	0x73, 0x6b, 0x2f, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x67, 0x0a, 0x08, 0x47, 0x61, 0x6d,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x6d, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x3a, 0x01, 0x2a, 0x22, 0x16, 0x2f, 0x73, 0x74, 0x2d,
	0x67, 0x61, 0x6d, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x69, 0x6e,
	0x66, 0x6f, 0x12, 0x7c, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x27, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x21, 0x3a,
	0x01, 0x2a, 0x22, 0x1c, 0x2f, 0x73, 0x74, 0x2d, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2f, 0x76, 0x31,
	0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2f, 0x67, 0x65, 0x74,
	0x12, 0x80, 0x01, 0x0a, 0x0e, 0x52, 0x65, 0x61, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x12, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x28, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x22, 0x3a, 0x01, 0x2a, 0x22, 0x1d, 0x2f, 0x73, 0x74, 0x2d, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2f,
	0x76, 0x31, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2f, 0x72,
	0x65, 0x61, 0x64, 0x12, 0x78, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x6d, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x26, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x20, 0x3a, 0x01, 0x2a,
	0x22, 0x1b, 0x2f, 0x73, 0x74, 0x2d, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x67,
	0x61, 0x6d, 0x65, 0x2f, 0x64, 0x69, 0x63, 0x74, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x78, 0x0a,
	0x0b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x12, 0x1f, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x29, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x23, 0x3a, 0x01, 0x2a, 0x22, 0x1e, 0x2f, 0x73, 0x74, 0x2d, 0x67, 0x61, 0x6d,
	0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x2f, 0x73, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x42, 0x39, 0x0a, 0x0b, 0x61, 0x70, 0x69, 0x2e, 0x67,
	0x61, 0x6d, 0x65, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x75, 0x6c, 0x75, 0x2d, 0x6c, 0x73, 0x2f, 0x73, 0x74, 0x2d,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x76, 0x31, 0x3b,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_v1_game_proto_rawDescOnce sync.Once
	file_game_v1_game_proto_rawDescData = file_game_v1_game_proto_rawDesc
)

func file_game_v1_game_proto_rawDescGZIP() []byte {
	file_game_v1_game_proto_rawDescOnce.Do(func() {
		file_game_v1_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_v1_game_proto_rawDescData)
	})
	return file_game_v1_game_proto_rawDescData
}

var file_game_v1_game_proto_enumTypes = make([]protoimpl.EnumInfo, 12)
var file_game_v1_game_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_game_v1_game_proto_goTypes = []interface{}{
	(AnnouncementType)(0),           // 0: api.game.v1.AnnouncementType
	(TaskStatus)(0),                 // 1: api.game.v1.TaskStatus
	(RefreshCycle)(0),               // 2: api.game.v1.RefreshCycle
	(GameType)(0),                   // 3: api.game.v1.GameType
	(GameCategory)(0),               // 4: api.game.v1.GameCategory
	(GameNotifyType)(0),             // 5: api.game.v1.GameNotifyType
	(DeviceType)(0),                 // 6: api.game.v1.DeviceType
	(VersionType)(0),                // 7: api.game.v1.VersionType
	(TaskAction)(0),                 // 8: api.game.v1.TaskAction
	(TaskType)(0),                   // 9: api.game.v1.TaskType
	(TaskRechargeType)(0),           // 10: api.game.v1.TaskRechargeType
	(TaskGameType)(0),               // 11: api.game.v1.TaskGameType
	(*AnnouncementListRequest)(nil), // 12: api.game.v1.AnnouncementListRequest
	(*AnnouncementListReply)(nil),   // 13: api.game.v1.AnnouncementListReply
	(*AnnouncementListItem)(nil),    // 14: api.game.v1.AnnouncementListItem
	(*ActivityListRequest)(nil),     // 15: api.game.v1.ActivityListRequest
	(*ActivityListReply)(nil),       // 16: api.game.v1.ActivityListReply
	(*ActivityListItem)(nil),        // 17: api.game.v1.ActivityListItem
	(*TaskDetailRequest)(nil),       // 18: api.game.v1.TaskDetailRequest
	(*TaskDetailReply)(nil),         // 19: api.game.v1.TaskDetailReply
	(*TaskListItem)(nil),            // 20: api.game.v1.TaskListItem
	(*TaskListAwardItem)(nil),       // 21: api.game.v1.TaskListAwardItem
	(*TaskRewardRequest)(nil),       // 22: api.game.v1.TaskRewardRequest
	(*TaskRewardReply)(nil),         // 23: api.game.v1.TaskRewardReply
	(*GameInfoRequest)(nil),         // 24: api.game.v1.GameInfoRequest
	(*GameInfoReply)(nil),           // 25: api.game.v1.GameInfoReply
	(*GetGameNotifyRequest)(nil),    // 26: api.game.v1.GetGameNotifyRequest
	(*GetGameNotifyReply)(nil),      // 27: api.game.v1.GetGameNotifyReply
	(*ReadGameNotifyRequest)(nil),   // 28: api.game.v1.ReadGameNotifyRequest
	(*ReadGameNotifyReply)(nil),     // 29: api.game.v1.ReadGameNotifyReply
	(*GetAppConfigRequest)(nil),     // 30: api.game.v1.GetAppConfigRequest
	(*GetAppConfigReply)(nil),       // 31: api.game.v1.GetAppConfigReply
	(*GetAppConfigItem)(nil),        // 32: api.game.v1.GetAppConfigItem
	(*CheckSignupRequest)(nil),      // 33: api.game.v1.CheckSignupRequest
	(*CheckSignupReply)(nil),        // 34: api.game.v1.CheckSignupReply
	(*v1.Paginate)(nil),             // 35: api.common.v1.Paginate
}
var file_game_v1_game_proto_depIdxs = []int32{
	35, // 0: api.game.v1.AnnouncementListRequest.page:type_name -> api.common.v1.Paginate
	14, // 1: api.game.v1.AnnouncementListReply.list:type_name -> api.game.v1.AnnouncementListItem
	0,  // 2: api.game.v1.AnnouncementListItem.type:type_name -> api.game.v1.AnnouncementType
	35, // 3: api.game.v1.ActivityListRequest.page:type_name -> api.common.v1.Paginate
	17, // 4: api.game.v1.ActivityListReply.list:type_name -> api.game.v1.ActivityListItem
	20, // 5: api.game.v1.TaskDetailReply.list:type_name -> api.game.v1.TaskListItem
	1,  // 6: api.game.v1.TaskListItem.status:type_name -> api.game.v1.TaskStatus
	21, // 7: api.game.v1.TaskListItem.award:type_name -> api.game.v1.TaskListAwardItem
	3,  // 8: api.game.v1.GameInfoReply.game_type:type_name -> api.game.v1.GameType
	4,  // 9: api.game.v1.GameInfoReply.game_category:type_name -> api.game.v1.GameCategory
	5,  // 10: api.game.v1.GetGameNotifyRequest.notify_type:type_name -> api.game.v1.GameNotifyType
	5,  // 11: api.game.v1.ReadGameNotifyRequest.notify_type:type_name -> api.game.v1.GameNotifyType
	6,  // 12: api.game.v1.GetAppConfigRequest.device:type_name -> api.game.v1.DeviceType
	7,  // 13: api.game.v1.GetAppConfigRequest.version_type:type_name -> api.game.v1.VersionType
	32, // 14: api.game.v1.GetAppConfigReply.list:type_name -> api.game.v1.GetAppConfigItem
	12, // 15: api.game.v1.Game.AnnouncementList:input_type -> api.game.v1.AnnouncementListRequest
	15, // 16: api.game.v1.Game.ActivityList:input_type -> api.game.v1.ActivityListRequest
	18, // 17: api.game.v1.Game.TaskDetail:input_type -> api.game.v1.TaskDetailRequest
	22, // 18: api.game.v1.Game.TaskReward:input_type -> api.game.v1.TaskRewardRequest
	24, // 19: api.game.v1.Game.GameInfo:input_type -> api.game.v1.GameInfoRequest
	26, // 20: api.game.v1.Game.GetGameNotify:input_type -> api.game.v1.GetGameNotifyRequest
	28, // 21: api.game.v1.Game.ReadGameNotify:input_type -> api.game.v1.ReadGameNotifyRequest
	30, // 22: api.game.v1.Game.GetAppConfig:input_type -> api.game.v1.GetAppConfigRequest
	33, // 23: api.game.v1.Game.CheckSignup:input_type -> api.game.v1.CheckSignupRequest
	13, // 24: api.game.v1.Game.AnnouncementList:output_type -> api.game.v1.AnnouncementListReply
	16, // 25: api.game.v1.Game.ActivityList:output_type -> api.game.v1.ActivityListReply
	19, // 26: api.game.v1.Game.TaskDetail:output_type -> api.game.v1.TaskDetailReply
	23, // 27: api.game.v1.Game.TaskReward:output_type -> api.game.v1.TaskRewardReply
	25, // 28: api.game.v1.Game.GameInfo:output_type -> api.game.v1.GameInfoReply
	27, // 29: api.game.v1.Game.GetGameNotify:output_type -> api.game.v1.GetGameNotifyReply
	29, // 30: api.game.v1.Game.ReadGameNotify:output_type -> api.game.v1.ReadGameNotifyReply
	31, // 31: api.game.v1.Game.GetAppConfig:output_type -> api.game.v1.GetAppConfigReply
	34, // 32: api.game.v1.Game.CheckSignup:output_type -> api.game.v1.CheckSignupReply
	24, // [24:33] is the sub-list for method output_type
	15, // [15:24] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_game_v1_game_proto_init() }
func file_game_v1_game_proto_init() {
	if File_game_v1_game_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_game_v1_game_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnnouncementListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_v1_game_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnnouncementListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_v1_game_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnnouncementListItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_v1_game_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivityListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_v1_game_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivityListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_v1_game_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivityListItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_v1_game_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskDetailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_v1_game_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskDetailReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_v1_game_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskListItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_v1_game_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskListAwardItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_v1_game_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskRewardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_v1_game_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskRewardReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_v1_game_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_v1_game_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_v1_game_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameNotifyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_v1_game_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameNotifyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_v1_game_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadGameNotifyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_v1_game_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadGameNotifyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_v1_game_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAppConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_v1_game_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAppConfigReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_v1_game_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAppConfigItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_v1_game_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckSignupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_v1_game_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckSignupReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_v1_game_proto_rawDesc,
			NumEnums:      12,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_v1_game_proto_goTypes,
		DependencyIndexes: file_game_v1_game_proto_depIdxs,
		EnumInfos:         file_game_v1_game_proto_enumTypes,
		MessageInfos:      file_game_v1_game_proto_msgTypes,
	}.Build()
	File_game_v1_game_proto = out.File
	file_game_v1_game_proto_rawDesc = nil
	file_game_v1_game_proto_goTypes = nil
	file_game_v1_game_proto_depIdxs = nil
}
